stockutil/stooq.py

从stooq的离线数据中读取出一个Yahoo格式的DF来

---

stockutil/stooq.py

加入在目录里寻找文件

---

requirements-dev.txt
requirements.txt
stockutil/wikipedia.py

加入获取spx成分清单的功能

---

stockutil/wikipedia.py

加入 #45 的空函数

---

sendxyh.py

为统计均线数量百分比加入空函数

---

.gitignore
musicbot/__main__.py
musicbot/config.py
musicbot/helpers/chat_id.py
musicbot/helpers/errors.py
musicbot/modules/song.py
musicbot/services/__init__.py
musicbot/services/callsmusic/__init__.py
musicbot/services/callsmusic/callsmusic.py
musicbot/services/converter/__init__.py
musicbot/services/converter/converter.py
musicbot/services/downloaders/__init__.py
musicbot/services/downloaders/youtube.py
musicbot/services/queues/__init__.py
musicbot/services/queues/queues.py
requirements-dev.txt
requirements.txt

已经可以向群里播放音乐了

---

musicbot/modules/play.py
musicbot/modules/song.py
musicbot/services/callsmusic/callsmusic.py
musicbot/services/converter/converter.py

现在支持 /join /leave命令让音乐播放机器人加入和离开语音
开始播放音乐时音乐播放机器人会发出正在播放的音乐信息了
#50 又更进了一步了

为播放时的bot与userbot交互进一步进行了研究与实现

---

musicbot/modules/song.py
musicbot/services/callsmusic/__init__.py
musicbot/services/callsmusic/callsmusic.py
musicbot/services/modules/control.py
musicbot/services/queues/__init__.py
musicbot/services/queues/queues.py
shell/crontab

播放行为基本了解清楚了

---

requirements-dev.txt
requirements.txt

需要youtube-search了

---

sendxyh.py
stockutil/stooq.py
stockutil/wikipedia.py

新版本的夕阳红到来啦

---

.gitignore
main.py
sendxyh.py
shell/sendxyh.sh

也就是说什么都不设置的话，就是在当前工程目录里
所以在.gitignore里加入data目录
fix #74

将存储stooq文件的目录变为config目录

---

sendxyh.py

日期参数处理还是有点问题

---

Dockerfile
README.md

变更一下Dockerfile

---

Dockerfile
README.md

将启动sendxyh变为启动bot

---

bot.py
cmdproc/groupcmd.py

基本上是最后的完善了

---

cmdproc/reportcmd.py

踢了以后，再加一个反馈消息

---

cmdproc/reportcmd.py

用一个更好的方法进行DEBUG，同时解决一个bug

---

cmdproc/reportcmd.py

把不是管理员的群id罗列出来

---

cmdproc/reportcmd.py

fix 无转发没有解析Markdown的bug

---

cmdproc/groupcmd.py

加入进群不说话会被踢的说明

---

config.py
example.env
sendmmt.py
sendxyh.py

准备发布版本的周边准备

---

sendxyh.py
stockutil/index.py
stockutil/ticker.py
tests/stockutil/test_index.py
tests/stockutil/test_ticker.py

加入Ben的相关改进

---

cmdproc/mmtcmd.py
tests/cmdproc/test_mmtcmd.py

1. 加入alert的功能；如果非提问用户点击，弹出alert 窗口
2. 加入编辑回复信息的功能
3. 判断endtime的时间是否比当前日期大
4. 修改了几个pytest的测试用例
5. 如果用户不输入时间， 自动更新成当年的1月1日 到今天的日期

加入alert的功能；并加入编辑回复信息的功能

---

sendxyh.py
stockutil/index.py
stockutil/ticker.py
tests/stockutil/test_index.py
tests/stockutil/test_ticker.py

给正盈利百分比加上“+”  删除计算交易量相关的函数和msg内容
